apiVersion: v2
name: ghost
description: Blog Publishing Platform 

type: application

# This is the chart version. 
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "5.75.1"
