# Default values for ghost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ghost

image:
  repository: docker.io/ghost
  tag: "5.75.1"

service:
  port: 2368

route:
  hostname: ghost

pvc:
  requests:
    storage: 101Mi 
