apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Applications/bgd/overlays/cluster-h2qfg/
    repoURL: https://github.com/tale-toul/ocp-gitops/
    targetRevision: arcentric
