apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: my-ca-issuer
  name: bgd
  namespace: bgd
spec:
  rules:
  - host: bgd.apps.{{  }} #<-- Patch with correct route domain
    http:
      paths:
      - backend:
          service:
            name: bgd
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bgd.apps.{{ }}  #<-- Patch with correct route domain
    secretName: bgd-ingress-cert
