---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: csv-check
  namespace: cert-manager-operator
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.11
          command:
            - /bin/bash
            - -c
            - |
              date
              echo "Wait for operator to install"
