apiVersion: bitnami.com/v1alpha1
kind: SealedSecretController
metadata:
  name: sealedsecretcontroller
  namespace: sealed-secrets
spec:
  image:
    repository: "{{ SSC_image }}"
    pullPolicy: IfNotPresent
  controller:
    create: true
  serviceAccount:
    create: true
    name: ''
  rbac:
    create: true
    pspEnabled: false
  secretName: sealed-secrets-key
  ingress:
    enabled: false
    path: /v1/cert.pem
    hosts:
      - chart-example.local
  crd:
    create: true
    keep: true
  networkPolicy: false
  securityContext:
    runAsUser: ''
    fsGroup: ''
  priorityClassName: ''
