apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghost
  name: ghost
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ghost
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-pvc
      serviceAccountName: ghost
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: ghost
        ports:
          - containerPort: 2368
        env:
          - name: NODE_ENV
            value: development
          - name: url
            value: http://{{ .Values.route.hostname }}.{{ (lookup "operator.openshift.io/v1" "IngressController" "openshift-ingress-operator" "default" ).status.domain }} 
          - name: database__connection__filename
            value: /var/lib/ghost/content/data/ghost.db
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/lib/ghost/content
            name: ghost-data
