apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testero-t1
  namespace: openshift-gitops
spec:
  destination:
    namespace: resourcet1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/testero
    repoURL: https://github.com/tale-toul/ocp-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
