apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machineAPI
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: MachineAPI
    repoURL: https://github.com/tale-toul/ocp-gitops/
    targetRevision: "4.7"

