---
- name: Configure OCP 4 cluster
  hosts: localhost
  connection: local
  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ api_entrypoint }}"
      ca_cert: "{{ api_ca_cert }}"
  tasks:
    - name: Load user credentials for OCP
      include_vars: 
        file: group_vars/user_credentials.vault
      no_log: true
        #    - name: Log into OCP to obtain access token
        #      k8s_auth:
        #        host: "{{ api_entrypoint }}"
        #        validate_certs: false
        #        username: "{{ ocp_user }}"
        #        password: "{{ ocp_pass }}"
        #      register: _auth_result
    - name: Install GitOps operator
      include_role:
        name: argocd_install
      when: argocd_install | bool
    - name: Set up htpass identity manager
      include_role:
        name: htpass_idm
      when: htpass_idm | bool
...
