apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: dXNlcjE6JDJ5JDA1JHhybFEvd3UvdGU4bXJPRWZXMWZuRy5rSi95QzZjbjhUZHVQMUlNb0JhdWhOSk1IWGpUaDFTCnVzZXIyOiRhcHIxJHZNbzVqcGJQJDVVRE04TENQMWdycDJzM3JWSVhFei4K
