---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: htpass-wait-job
  namespace: openshift-gitops
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.11
          command:
            - /bin/bash
            - -c
            - |
              echo "Wait for Authentication cluster operator to detect the change"
              sleep $SLEEP
              until oc wait co/authentication --for condition=Progressing --timeout 60s
              do
                echo -n "...still waiting for Authentication cluster operator to detect the change"
                sleep $SLEEP
              done
              echo "Change detected by authentication cluster operator"
              echo "Wait for Authentication deployment to complete"
              until oc rollout status deployment/oauth-openshift -n openshift-authentication
              echo "Rollout completed. Authentication Operator ready to accept new users"
          imagePullPolicy: Always
          name: htpass-wait-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: openshift-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 30
