---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: htpass-wait-job
  namespace: openshift-gitops
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.11
          command:
            - /bin/bash
            - -c
            - |
              date
              echo "Wait for Authentication Cluster Operator to detect the change"
              for x in 1 2 3 
              do
                oc wait co/authentication --for condition=Progressing --timeout 20s
                echo -e "\n...Still waiting for Authentication Cluster Operator to detect the change."
                date
                sleep $SLEEP
                if [ $x -eq 3 ]
                then
                  echo -e "\nChange NOT detected by the Authentication Operator. This is normal if only the secret was updated"
                  date
                fi
              done
              date
              echo -e "\nWait for Authentication deployment to complete"
              oc rollout status deployment/oauth-openshift -n openshift-authentication
              date
              echo -e "\nRollout completed. Authentication Operator ready to accept new users"
          imagePullPolicy: Always
          name: htpass-wait-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: openshift-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 30
